# Generated by Django 5.2.3 on 2025-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sender',
            field=models.CharField(default='+13853967824'),
        ),
    ]
